#!/bin/sh
###
### gunicorn3 dashboard:app.server --config gunicorn_conf.py
###
cp --verbose gunicorn.socket /etc/systemd/system/
cp --verbose gunicorn.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now gunicorn.socket
systemctl enable --now gunicorn.service
