#!/bin/sh
logpath='/home/jay/workspace-sensors2/FirstDashboard/log/'
logname='payload.log'
script='/home/jay/workspace-sensors2/FirstDashboard/Broker/payloadbrker.py'
/usr/bin/python3 $script >> $logpath$logname 2>&1
